name: publish-adr
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/publish-adr.yml
      - docs/**

env:
  # renovate: datasource=github-tags depName=gohugoio/hugo
  HUGO_VERSION: 0.125.7

permissions: read-all

jobs:
  publish-adr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0 # required by Log4brains to work correctly (needs the whole Git history)
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: ${{ env.HUGO_VERSION }}

      - name: Install Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "16"

      - name: Prepare public directory
        run: |
          set -euxo pipefail
          mkdir gh-pages
          cp LICENSE README.md gh-pages/

      - name: Build hugo pages
        run: |
          hugo --gc --destination gh-pages

      - name: Install and Build Log4brains
        run: |
          npm install -g log4brains
          mkdir -pv gh-pages/log4brains
          cd log4brains
          log4brains build --basePath "/${GITHUB_REPOSITORY#*/}/log4brains" --out ../gh-pages/log4brains

      - name: Build MADR
        uses: helaili/jekyll-action@v2
        with:
          jekyll_src: madr
          build_only: true
          build_dir: gh-pages/madr

      - name: Deploy
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
          force_orphan: true
